### PR TITLE
Fix setup.py to install pygments dependency

### PR DESCRIPTION
**Pull request by paparent**
This branch make the installation to automaticly install pygments when we `pip install hamlpy`.

### CODE REVIEW

**Comment by bcoughlan** [comment]
Hi paparent,

Your commit removes Django as a dependency? Is this intentional?

Regards,
Bary

**Comment by paparent** [comment]
Oops, forgot to push! Django is indeed needed for the command to run! 

PA

**Comment by bcoughlan** [comment]
I don't know if the requirements are case-sensitive, be sure to test your changes if you're not sure either!

**Comment by paparent** [comment]
You can try by yourself.. http://pypi.python.org/pypi/django is giving me a 404, while http://pypi.python.org/pypi/Django a 200 :)

**Pull request merged**
