### PR TITLE
Added HTML-like tags support

### PR DESCRIPTION
**Pull request by syabro**
For example %a(href=http://ya.ru rel=mylink)

### CODE REVIEW

**Comment by hph** [comment]
I like the idea.
:+1:

**Comment by jessemiller** [comment]
This is looking good. Do you know what the license is on the structmatch code pulled in with this?

**Comment by syabro** [comment]
Don't think it's a good idea now.
Doesn't work well.
1. It doesn't allow to use brackets inside quotes like `%a(onclick="alert()")`
2. It doesn't allow to use unicode inside quotes
3. Also few bugs with using single-quotes and atribute name without values like %input(selected)

I tried to update detecting regexp not to math brackets inside quotes but stuck :(

**Comment by jessemiller** [comment]
Ok, I appreciate the honest feedback. Closing this for now..

**Pull request closed without merging**
